/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AddressVerificationMethod from './AddressVerificationMethod';
import AddressVerificationStatus from './AddressVerificationStatus';

/**
 * The AddressVerification model module.
 * @module model/AddressVerification
 */
class AddressVerification {
    /**
     * Constructs a new <code>AddressVerification</code>.
     * Summary of a self-custody address verification record. Returned as items in [List address verifications](#operation/list_address_verifications). Call [Get address verification](#operation/get_address_verification) with &#x60;verification_id&#x60; to retrieve method-specific provenance (&#x60;satoshi_test_detail&#x60; / &#x60;signature_detail&#x60;). 
     * @alias module:model/AddressVerification
     * @param verification_id {String} The unique identifier of this verification record.
     * @param address {String} The counterparty (self-custody) wallet address being verified.
     * @param chain_id {String} The chain on which this address is verified.
     * @param status {module:model/AddressVerificationStatus} 
     * @param verification_method {module:model/AddressVerificationMethod} 
     */
    constructor(verification_id, address, chain_id, status, verification_method) { 
        
        AddressVerification.initialize(this, verification_id, address, chain_id, status, verification_method);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, verification_id, address, chain_id, status, verification_method) { 
        obj['verification_id'] = verification_id;
        obj['address'] = address;
        obj['chain_id'] = chain_id;
        obj['status'] = status;
        obj['verification_method'] = verification_method;
    }

    /**
     * Constructs a <code>AddressVerification</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddressVerification} obj Optional instance to populate.
     * @return {module:model/AddressVerification} The populated <code>AddressVerification</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddressVerification();

            if (data.hasOwnProperty('verification_id')) {
                obj['verification_id'] = ApiClient.convertToType(data['verification_id'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('chain_id')) {
                obj['chain_id'] = ApiClient.convertToType(data['chain_id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = AddressVerificationStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('verification_method')) {
                obj['verification_method'] = AddressVerificationMethod.constructFromObject(data['verification_method']);
            }
            if (data.hasOwnProperty('verified_at')) {
                obj['verified_at'] = ApiClient.convertToType(data['verified_at'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddressVerification</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddressVerification</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AddressVerification.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['verification_id'] && !(typeof data['verification_id'] === 'string' || data['verification_id'] instanceof String)) {
            throw new Error("Expected the field `verification_id` to be a primitive type in the JSON string but got " + data['verification_id']);
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }
        // ensure the json data is a string
        if (data['chain_id'] && !(typeof data['chain_id'] === 'string' || data['chain_id'] instanceof String)) {
            throw new Error("Expected the field `chain_id` to be a primitive type in the JSON string but got " + data['chain_id']);
        }

        return true;
    }


}

AddressVerification.RequiredProperties = ["verification_id", "address", "chain_id", "status", "verification_method"];

/**
 * The unique identifier of this verification record.
 * @member {String} verification_id
 */
AddressVerification.prototype['verification_id'] = undefined;

/**
 * The counterparty (self-custody) wallet address being verified.
 * @member {String} address
 */
AddressVerification.prototype['address'] = undefined;

/**
 * The chain on which this address is verified.
 * @member {String} chain_id
 */
AddressVerification.prototype['chain_id'] = undefined;

/**
 * @member {module:model/AddressVerificationStatus} status
 */
AddressVerification.prototype['status'] = undefined;

/**
 * @member {module:model/AddressVerificationMethod} verification_method
 */
AddressVerification.prototype['verification_method'] = undefined;

/**
 * Timestamp (milliseconds) when verification completed. `null` while `status=PENDING` or `FAILED`.
 * @member {Number} verified_at
 */
AddressVerification.prototype['verified_at'] = undefined;






export default AddressVerification;

