/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SatoshiTestChallenge from './SatoshiTestChallenge';
import SatoshiTestChallengeStatus from './SatoshiTestChallengeStatus';

/**
 * The AddressVerificationDetailSatoshiTestDetail model module.
 * @module model/AddressVerificationDetailSatoshiTestDetail
 */
class AddressVerificationDetailSatoshiTestDetail {
    /**
     * Constructs a new <code>AddressVerificationDetailSatoshiTestDetail</code>.
     * The latest Satoshi Test challenge associated with this verification. Present only when &#x60;verification_method&#x3D;SATOSHI_TEST&#x60;. 
     * @alias module:model/AddressVerificationDetailSatoshiTestDetail
     * @implements module:model/SatoshiTestChallenge
     * @param challenge_id {String} The unique identifier of the Satoshi Test challenge.
     * @param from_address {String} The counterparty (self-custody) wallet address that must transfer the micro-deposit.
     * @param to_address {String} The Cobo-generated verification address that will receive the micro-deposit.
     * @param amount {String} The exact amount (in the token's smallest unit) that must be transferred. The amount is unique per challenge and is used together with `to_address` to identify a matching on-chain transfer. 
     * @param token_id {String} The ID of the token used for the micro-deposit (typically the chain's native asset).
     * @param chain_id {String} The chain on which the micro-deposit is expected.
     * @param status {module:model/SatoshiTestChallengeStatus} 
     * @param remaining_seconds {Number} Remaining time (in seconds) before the challenge expires. `0` when the challenge is not yet submitted or has already completed/expired. 
     */
    constructor(challenge_id, from_address, to_address, amount, token_id, chain_id, status, remaining_seconds) { 
        SatoshiTestChallenge.initialize(this, challenge_id, from_address, to_address, amount, token_id, chain_id, status, remaining_seconds);
        AddressVerificationDetailSatoshiTestDetail.initialize(this, challenge_id, from_address, to_address, amount, token_id, chain_id, status, remaining_seconds);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, challenge_id, from_address, to_address, amount, token_id, chain_id, status, remaining_seconds) { 
        obj['challenge_id'] = challenge_id;
        obj['from_address'] = from_address;
        obj['to_address'] = to_address;
        obj['amount'] = amount;
        obj['token_id'] = token_id;
        obj['chain_id'] = chain_id;
        obj['status'] = status;
        obj['remaining_seconds'] = remaining_seconds;
    }

    /**
     * Constructs a <code>AddressVerificationDetailSatoshiTestDetail</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddressVerificationDetailSatoshiTestDetail} obj Optional instance to populate.
     * @return {module:model/AddressVerificationDetailSatoshiTestDetail} The populated <code>AddressVerificationDetailSatoshiTestDetail</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddressVerificationDetailSatoshiTestDetail();
            SatoshiTestChallenge.constructFromObject(data, obj);

            if (data.hasOwnProperty('challenge_id')) {
                obj['challenge_id'] = ApiClient.convertToType(data['challenge_id'], 'String');
            }
            if (data.hasOwnProperty('from_address')) {
                obj['from_address'] = ApiClient.convertToType(data['from_address'], 'String');
            }
            if (data.hasOwnProperty('to_address')) {
                obj['to_address'] = ApiClient.convertToType(data['to_address'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
            }
            if (data.hasOwnProperty('token_id')) {
                obj['token_id'] = ApiClient.convertToType(data['token_id'], 'String');
            }
            if (data.hasOwnProperty('chain_id')) {
                obj['chain_id'] = ApiClient.convertToType(data['chain_id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = SatoshiTestChallengeStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('remaining_seconds')) {
                obj['remaining_seconds'] = ApiClient.convertToType(data['remaining_seconds'], 'Number');
            }
            if (data.hasOwnProperty('matched_txid')) {
                obj['matched_txid'] = ApiClient.convertToType(data['matched_txid'], 'String');
            }
            if (data.hasOwnProperty('started_at')) {
                obj['started_at'] = ApiClient.convertToType(data['started_at'], 'Number');
            }
            if (data.hasOwnProperty('expires_at')) {
                obj['expires_at'] = ApiClient.convertToType(data['expires_at'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddressVerificationDetailSatoshiTestDetail</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddressVerificationDetailSatoshiTestDetail</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AddressVerificationDetailSatoshiTestDetail.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['challenge_id'] && !(typeof data['challenge_id'] === 'string' || data['challenge_id'] instanceof String)) {
            throw new Error("Expected the field `challenge_id` to be a primitive type in the JSON string but got " + data['challenge_id']);
        }
        // ensure the json data is a string
        if (data['from_address'] && !(typeof data['from_address'] === 'string' || data['from_address'] instanceof String)) {
            throw new Error("Expected the field `from_address` to be a primitive type in the JSON string but got " + data['from_address']);
        }
        // ensure the json data is a string
        if (data['to_address'] && !(typeof data['to_address'] === 'string' || data['to_address'] instanceof String)) {
            throw new Error("Expected the field `to_address` to be a primitive type in the JSON string but got " + data['to_address']);
        }
        // ensure the json data is a string
        if (data['amount'] && !(typeof data['amount'] === 'string' || data['amount'] instanceof String)) {
            throw new Error("Expected the field `amount` to be a primitive type in the JSON string but got " + data['amount']);
        }
        // ensure the json data is a string
        if (data['token_id'] && !(typeof data['token_id'] === 'string' || data['token_id'] instanceof String)) {
            throw new Error("Expected the field `token_id` to be a primitive type in the JSON string but got " + data['token_id']);
        }
        // ensure the json data is a string
        if (data['chain_id'] && !(typeof data['chain_id'] === 'string' || data['chain_id'] instanceof String)) {
            throw new Error("Expected the field `chain_id` to be a primitive type in the JSON string but got " + data['chain_id']);
        }
        // ensure the json data is a string
        if (data['matched_txid'] && !(typeof data['matched_txid'] === 'string' || data['matched_txid'] instanceof String)) {
            throw new Error("Expected the field `matched_txid` to be a primitive type in the JSON string but got " + data['matched_txid']);
        }

        return true;
    }


}

AddressVerificationDetailSatoshiTestDetail.RequiredProperties = ["challenge_id", "from_address", "to_address", "amount", "token_id", "chain_id", "status", "remaining_seconds"];

/**
 * The unique identifier of the Satoshi Test challenge.
 * @member {String} challenge_id
 */
AddressVerificationDetailSatoshiTestDetail.prototype['challenge_id'] = undefined;

/**
 * The counterparty (self-custody) wallet address that must transfer the micro-deposit.
 * @member {String} from_address
 */
AddressVerificationDetailSatoshiTestDetail.prototype['from_address'] = undefined;

/**
 * The Cobo-generated verification address that will receive the micro-deposit.
 * @member {String} to_address
 */
AddressVerificationDetailSatoshiTestDetail.prototype['to_address'] = undefined;

/**
 * The exact amount (in the token's smallest unit) that must be transferred. The amount is unique per challenge and is used together with `to_address` to identify a matching on-chain transfer. 
 * @member {String} amount
 */
AddressVerificationDetailSatoshiTestDetail.prototype['amount'] = undefined;

/**
 * The ID of the token used for the micro-deposit (typically the chain's native asset).
 * @member {String} token_id
 */
AddressVerificationDetailSatoshiTestDetail.prototype['token_id'] = undefined;

/**
 * The chain on which the micro-deposit is expected.
 * @member {String} chain_id
 */
AddressVerificationDetailSatoshiTestDetail.prototype['chain_id'] = undefined;

/**
 * @member {module:model/SatoshiTestChallengeStatus} status
 */
AddressVerificationDetailSatoshiTestDetail.prototype['status'] = undefined;

/**
 * Remaining time (in seconds) before the challenge expires. `0` when the challenge is not yet submitted or has already completed/expired. 
 * @member {Number} remaining_seconds
 */
AddressVerificationDetailSatoshiTestDetail.prototype['remaining_seconds'] = undefined;

/**
 * The on-chain transaction hash of the matching transfer, once matched.
 * @member {String} matched_txid
 */
AddressVerificationDetailSatoshiTestDetail.prototype['matched_txid'] = undefined;

/**
 * Timestamp (milliseconds) when the challenge was submitted and the countdown started.
 * @member {Number} started_at
 */
AddressVerificationDetailSatoshiTestDetail.prototype['started_at'] = undefined;

/**
 * Timestamp (milliseconds) when the challenge will expire if not matched.
 * @member {Number} expires_at
 */
AddressVerificationDetailSatoshiTestDetail.prototype['expires_at'] = undefined;


// Implement SatoshiTestChallenge interface:
/**
 * The unique identifier of the Satoshi Test challenge.
 * @member {String} challenge_id
 */
SatoshiTestChallenge.prototype['challenge_id'] = undefined;
/**
 * The counterparty (self-custody) wallet address that must transfer the micro-deposit.
 * @member {String} from_address
 */
SatoshiTestChallenge.prototype['from_address'] = undefined;
/**
 * The Cobo-generated verification address that will receive the micro-deposit.
 * @member {String} to_address
 */
SatoshiTestChallenge.prototype['to_address'] = undefined;
/**
 * The exact amount (in the token's smallest unit) that must be transferred. The amount is unique per challenge and is used together with `to_address` to identify a matching on-chain transfer. 
 * @member {String} amount
 */
SatoshiTestChallenge.prototype['amount'] = undefined;
/**
 * The ID of the token used for the micro-deposit (typically the chain's native asset).
 * @member {String} token_id
 */
SatoshiTestChallenge.prototype['token_id'] = undefined;
/**
 * The chain on which the micro-deposit is expected.
 * @member {String} chain_id
 */
SatoshiTestChallenge.prototype['chain_id'] = undefined;
/**
 * @member {module:model/SatoshiTestChallengeStatus} status
 */
SatoshiTestChallenge.prototype['status'] = undefined;
/**
 * Remaining time (in seconds) before the challenge expires. `0` when the challenge is not yet submitted or has already completed/expired. 
 * @member {Number} remaining_seconds
 */
SatoshiTestChallenge.prototype['remaining_seconds'] = undefined;
/**
 * The on-chain transaction hash of the matching transfer, once matched.
 * @member {String} matched_txid
 */
SatoshiTestChallenge.prototype['matched_txid'] = undefined;
/**
 * Timestamp (milliseconds) when the challenge was submitted and the countdown started.
 * @member {Number} started_at
 */
SatoshiTestChallenge.prototype['started_at'] = undefined;
/**
 * Timestamp (milliseconds) when the challenge will expire if not matched.
 * @member {Number} expires_at
 */
SatoshiTestChallenge.prototype['expires_at'] = undefined;




export default AddressVerificationDetailSatoshiTestDetail;

