/**
 * Cobo Wallet as a Service 2.0
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MPCDelegate from './MPCDelegate';
import MpcSigningGroup from './MpcSigningGroup';

/**
 * The CoboSafeDelegate model module.
 * @module model/CoboSafeDelegate
 * @version 0.4.5
 */
class CoboSafeDelegate {
    /**
     * Constructs a new <code>CoboSafeDelegate</code>.
     * @alias module:model/CoboSafeDelegate
     * @param {(module:model/MPCDelegate)} instance The actual instance to initialize CoboSafeDelegate.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "MPCDelegate") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MPCDelegate.validateJSON(instance); // throw an exception if no match
                // create MPCDelegate from JS object
                this.actualInstance = MPCDelegate.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MPCDelegate
            errorMessages.push("Failed to construct MPCDelegate: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `CoboSafeDelegate` with oneOf schemas MPCDelegate. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `CoboSafeDelegate` with oneOf schemas MPCDelegate. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>CoboSafeDelegate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CoboSafeDelegate} obj Optional instance to populate.
     * @return {module:model/CoboSafeDelegate} The populated <code>CoboSafeDelegate</code> instance.
     */
    static constructFromObject(data, obj) {
        return new CoboSafeDelegate(data);
    }

    /**
     * Gets the actual instance, which can be <code>MPCDelegate</code>.
     * @return {(module:model/MPCDelegate)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>MPCDelegate</code>.
     * @param {(module:model/MPCDelegate)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = CoboSafeDelegate.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of CoboSafeDelegate from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/CoboSafeDelegate} An instance of CoboSafeDelegate.
     */
    static fromJSON = function(json_string){
        return CoboSafeDelegate.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * The delegator subtype. Possible values include: - `Org-Controlled`: MPC Wallets (Organization-Controlled Wallets). - `User-Controlled`: MPC Wallets (User-Controlled Wallets). 
 * @member {module:model/CoboSafeDelegate.DelegateTypeEnum} delegate_type
 * @default 'Org-Controlled'
 */
CoboSafeDelegate.prototype['delegate_type'] = 'Org-Controlled';

/**
 * The wallet ID of the Delegate. This is required when initiating a transfer from Smart Contract Wallets (Safe{Wallet}).
 * @member {String} wallet_id
 */
CoboSafeDelegate.prototype['wallet_id'] = undefined;

/**
 * The wallet address of the Delegate. This is required when initiating a transfer from Smart Contract Wallets (Safe{Wallet}).
 * @member {String} address
 */
CoboSafeDelegate.prototype['address'] = undefined;

/**
 * @member {module:model/MpcSigningGroup} mpc_used_key_share_holder_group
 */
CoboSafeDelegate.prototype['mpc_used_key_share_holder_group'] = undefined;


CoboSafeDelegate.OneOf = ["MPCDelegate"];

export default CoboSafeDelegate;

