/**
 * Cobo Wallet as a Service 2.0
 * Cobo WaaS 2.0 enables you to programmatically access Cobo's full suite of crypto wallet technologies with powerful and flexible access controls.  # Wallet technologies - Custodial Wallet - MPC Wallet - Smart Contract Wallet (Based on Safe{Wallet}) - Exchange Wallet  # Risk Control technologies - Workflow - Access Control List (ACL)  # Risk Control targets - Wallet Management   - User/team and their permission management   - Risk control configurations, e.g. whitelist, blacklist, rate-limiting etc. - Blockchain Interaction   - Crypto transfer   - Smart Contract Invocation  # Important HTTPS only. RESTful, resource oriented  # Get Started Set up your APIs or get authorization  # Authentication and Authorization CoboAuth  # Request and Response application/json  # Error Handling  ### Common error codes | Error Code | Description | | -- | -- |  ### API-specific error codes For error codes that are dedicated to a specific API, see the Error codes section in each API specification, for example, /v3/wallets.  # Rate and Usage Limiting  # Idempotent Request  # Pagination # Support [Developer Hub](https://cobo.com/developers) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EvmEip1559FeeSlow from './EvmEip1559FeeSlow';
import FeeType from './FeeType';

/**
 * The EvmEip1559Fee model module.
 * @module model/EvmEip1559Fee
 * @version 0.1.0
 */
class EvmEip1559Fee {
    /**
     * Constructs a new <code>EvmEip1559Fee</code>.
     * The eip1559 fee data for estimate fees or transfer.
     * @alias module:model/EvmEip1559Fee
     * @param feeType {module:model/FeeType} 
     * @param standard {module:model/EvmEip1559FeeSlow} 
     */
    constructor(feeType, standard) { 
        
        EvmEip1559Fee.initialize(this, feeType, standard);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, feeType, standard) { 
        obj['fee_type'] = feeType;
        obj['standard'] = standard;
    }

    /**
     * Constructs a <code>EvmEip1559Fee</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EvmEip1559Fee} obj Optional instance to populate.
     * @return {module:model/EvmEip1559Fee} The populated <code>EvmEip1559Fee</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EvmEip1559Fee();

            if (data.hasOwnProperty('fee_type')) {
                obj['fee_type'] = FeeType.constructFromObject(data['fee_type']);
            }
            if (data.hasOwnProperty('slow')) {
                obj['slow'] = EvmEip1559FeeSlow.constructFromObject(data['slow']);
            }
            if (data.hasOwnProperty('standard')) {
                obj['standard'] = EvmEip1559FeeSlow.constructFromObject(data['standard']);
            }
            if (data.hasOwnProperty('fast')) {
                obj['fast'] = EvmEip1559FeeSlow.constructFromObject(data['fast']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EvmEip1559Fee</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EvmEip1559Fee</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EvmEip1559Fee.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `slow`
        if (data['slow']) { // data not null
          EvmEip1559FeeSlow.validateJSON(data['slow']);
        }
        // validate the optional field `standard`
        if (data['standard']) { // data not null
          EvmEip1559FeeSlow.validateJSON(data['standard']);
        }
        // validate the optional field `fast`
        if (data['fast']) { // data not null
          EvmEip1559FeeSlow.validateJSON(data['fast']);
        }

        return true;
    }


}

EvmEip1559Fee.RequiredProperties = ["fee_type", "standard"];

/**
 * @member {module:model/FeeType} fee_type
 */
EvmEip1559Fee.prototype['fee_type'] = undefined;

/**
 * @member {module:model/EvmEip1559FeeSlow} slow
 */
EvmEip1559Fee.prototype['slow'] = undefined;

/**
 * @member {module:model/EvmEip1559FeeSlow} standard
 */
EvmEip1559Fee.prototype['standard'] = undefined;

/**
 * @member {module:model/EvmEip1559FeeSlow} fast
 */
EvmEip1559Fee.prototype['fast'] = undefined;






export default EvmEip1559Fee;

