/**
 * Cobo Wallet as a Service 2.0
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EvmEip1559FeeSlow from './EvmEip1559FeeSlow';
import FeeType from './FeeType';

/**
 * The EvmEip1559Fee model module.
 * @module model/EvmEip1559Fee
 * @version 0.4.4
 */
class EvmEip1559Fee {
    /**
     * Constructs a new <code>EvmEip1559Fee</code>.
     * The estimated transaction fee based on the EIP-1559 fee model.
     * @alias module:model/EvmEip1559Fee
     * @param feeType {module:model/FeeType} 
     * @param recommended {module:model/EvmEip1559FeeSlow} 
     */
    constructor(feeType, recommended) { 
        
        EvmEip1559Fee.initialize(this, feeType, recommended);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, feeType, recommended) { 
        obj['fee_type'] = feeType;
        obj['recommended'] = recommended;
    }

    /**
     * Constructs a <code>EvmEip1559Fee</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EvmEip1559Fee} obj Optional instance to populate.
     * @return {module:model/EvmEip1559Fee} The populated <code>EvmEip1559Fee</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EvmEip1559Fee();

            if (data.hasOwnProperty('fee_type')) {
                obj['fee_type'] = FeeType.constructFromObject(data['fee_type']);
            }
            if (data.hasOwnProperty('token_id')) {
                obj['token_id'] = ApiClient.convertToType(data['token_id'], 'String');
            }
            if (data.hasOwnProperty('slow')) {
                obj['slow'] = EvmEip1559FeeSlow.constructFromObject(data['slow']);
            }
            if (data.hasOwnProperty('recommended')) {
                obj['recommended'] = EvmEip1559FeeSlow.constructFromObject(data['recommended']);
            }
            if (data.hasOwnProperty('fast')) {
                obj['fast'] = EvmEip1559FeeSlow.constructFromObject(data['fast']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EvmEip1559Fee</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EvmEip1559Fee</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EvmEip1559Fee.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['token_id'] && !(typeof data['token_id'] === 'string' || data['token_id'] instanceof String)) {
            throw new Error("Expected the field `token_id` to be a primitive type in the JSON string but got " + data['token_id']);
        }
        // validate the optional field `slow`
        if (data['slow']) { // data not null
          EvmEip1559FeeSlow.validateJSON(data['slow']);
        }
        // validate the optional field `recommended`
        if (data['recommended']) { // data not null
          EvmEip1559FeeSlow.validateJSON(data['recommended']);
        }
        // validate the optional field `fast`
        if (data['fast']) { // data not null
          EvmEip1559FeeSlow.validateJSON(data['fast']);
        }

        return true;
    }


}

EvmEip1559Fee.RequiredProperties = ["fee_type", "recommended"];

/**
 * @member {module:model/FeeType} fee_type
 */
EvmEip1559Fee.prototype['fee_type'] = undefined;

/**
 * The token ID of the transaction fee.
 * @member {String} token_id
 */
EvmEip1559Fee.prototype['token_id'] = undefined;

/**
 * @member {module:model/EvmEip1559FeeSlow} slow
 */
EvmEip1559Fee.prototype['slow'] = undefined;

/**
 * @member {module:model/EvmEip1559FeeSlow} recommended
 */
EvmEip1559Fee.prototype['recommended'] = undefined;

/**
 * @member {module:model/EvmEip1559FeeSlow} fast
 */
EvmEip1559Fee.prototype['fast'] = undefined;






export default EvmEip1559Fee;

