/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MerchantKycAddress from './MerchantKycAddress';
import MerchantKycCompanyAttachment from './MerchantKycCompanyAttachment';
import MerchantKycCompanyType from './MerchantKycCompanyType';
import MerchantKycPersonInfo from './MerchantKycPersonInfo';

/**
 * The MerchantKycCompanyInfo model module.
 * @module model/MerchantKycCompanyInfo
 */
class MerchantKycCompanyInfo {
    /**
     * Constructs a new <code>MerchantKycCompanyInfo</code>.
     * @alias module:model/MerchantKycCompanyInfo
     * @param company_type {module:model/MerchantKycCompanyType} 
     * @param listed {Boolean} Whether the company is listed.
     * @param attachments {Array.<module:model/MerchantKycCompanyAttachment>} The attachments of the company.
     * @param operation_address {module:model/MerchantKycAddress} 
     * @param identify_no {String} The company identification number.
     * @param company_name {String} The company name in local language.
     * @param company_name_en {String} The company name in English.
     * @param establish_date {String} The establishment date of the company.
     * @param commencement_date {String} The commencement date of the company.
     * @param valid_period {String} The valid period of the company registration.
     * @param register_address {module:model/MerchantKycAddress} 
     * @param legal_info {module:model/MerchantKycPersonInfo} 
     * @param ubo_infos {Array.<module:model/MerchantKycPersonInfo>} The ultimate beneficial owner information.
     */
    constructor(company_type, listed, attachments, operation_address, identify_no, company_name, company_name_en, establish_date, commencement_date, valid_period, register_address, legal_info, ubo_infos) { 
        
        MerchantKycCompanyInfo.initialize(this, company_type, listed, attachments, operation_address, identify_no, company_name, company_name_en, establish_date, commencement_date, valid_period, register_address, legal_info, ubo_infos);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, company_type, listed, attachments, operation_address, identify_no, company_name, company_name_en, establish_date, commencement_date, valid_period, register_address, legal_info, ubo_infos) { 
        obj['company_type'] = company_type;
        obj['listed'] = listed;
        obj['attachments'] = attachments;
        obj['operation_address'] = operation_address;
        obj['identify_no'] = identify_no;
        obj['company_name'] = company_name;
        obj['company_name_en'] = company_name_en;
        obj['establish_date'] = establish_date;
        obj['commencement_date'] = commencement_date;
        obj['valid_period'] = valid_period;
        obj['register_address'] = register_address;
        obj['legal_info'] = legal_info;
        obj['ubo_infos'] = ubo_infos;
    }

    /**
     * Constructs a <code>MerchantKycCompanyInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantKycCompanyInfo} obj Optional instance to populate.
     * @return {module:model/MerchantKycCompanyInfo} The populated <code>MerchantKycCompanyInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantKycCompanyInfo();

            if (data.hasOwnProperty('company_type')) {
                obj['company_type'] = MerchantKycCompanyType.constructFromObject(data['company_type']);
            }
            if (data.hasOwnProperty('listed')) {
                obj['listed'] = ApiClient.convertToType(data['listed'], 'Boolean');
            }
            if (data.hasOwnProperty('attachments')) {
                obj['attachments'] = ApiClient.convertToType(data['attachments'], [MerchantKycCompanyAttachment]);
            }
            if (data.hasOwnProperty('operation_address')) {
                obj['operation_address'] = MerchantKycAddress.constructFromObject(data['operation_address']);
            }
            if (data.hasOwnProperty('identify_no')) {
                obj['identify_no'] = ApiClient.convertToType(data['identify_no'], 'String');
            }
            if (data.hasOwnProperty('company_name')) {
                obj['company_name'] = ApiClient.convertToType(data['company_name'], 'String');
            }
            if (data.hasOwnProperty('company_name_en')) {
                obj['company_name_en'] = ApiClient.convertToType(data['company_name_en'], 'String');
            }
            if (data.hasOwnProperty('establish_date')) {
                obj['establish_date'] = ApiClient.convertToType(data['establish_date'], 'String');
            }
            if (data.hasOwnProperty('commencement_date')) {
                obj['commencement_date'] = ApiClient.convertToType(data['commencement_date'], 'String');
            }
            if (data.hasOwnProperty('valid_period')) {
                obj['valid_period'] = ApiClient.convertToType(data['valid_period'], 'String');
            }
            if (data.hasOwnProperty('register_address')) {
                obj['register_address'] = MerchantKycAddress.constructFromObject(data['register_address']);
            }
            if (data.hasOwnProperty('legal_info')) {
                obj['legal_info'] = MerchantKycPersonInfo.constructFromObject(data['legal_info']);
            }
            if (data.hasOwnProperty('ubo_infos')) {
                obj['ubo_infos'] = ApiClient.convertToType(data['ubo_infos'], [MerchantKycPersonInfo]);
            }
            if (data.hasOwnProperty('online_store_url')) {
                obj['online_store_url'] = ApiClient.convertToType(data['online_store_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MerchantKycCompanyInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MerchantKycCompanyInfo</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MerchantKycCompanyInfo.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['attachments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['attachments'])) {
                throw new Error("Expected the field `attachments` to be an array in the JSON data but got " + data['attachments']);
            }
            // validate the optional field `attachments` (array)
            for (const item of data['attachments']) {
                MerchantKycCompanyAttachment.validateJSON(item);
            };
        }
        // validate the optional field `operation_address`
        if (data['operation_address']) { // data not null
          if (!!MerchantKycAddress.validateJSON) {
            MerchantKycAddress.validateJSON(data['operation_address']);
          }
        }
        // ensure the json data is a string
        if (data['identify_no'] && !(typeof data['identify_no'] === 'string' || data['identify_no'] instanceof String)) {
            throw new Error("Expected the field `identify_no` to be a primitive type in the JSON string but got " + data['identify_no']);
        }
        // ensure the json data is a string
        if (data['company_name'] && !(typeof data['company_name'] === 'string' || data['company_name'] instanceof String)) {
            throw new Error("Expected the field `company_name` to be a primitive type in the JSON string but got " + data['company_name']);
        }
        // ensure the json data is a string
        if (data['company_name_en'] && !(typeof data['company_name_en'] === 'string' || data['company_name_en'] instanceof String)) {
            throw new Error("Expected the field `company_name_en` to be a primitive type in the JSON string but got " + data['company_name_en']);
        }
        // ensure the json data is a string
        if (data['establish_date'] && !(typeof data['establish_date'] === 'string' || data['establish_date'] instanceof String)) {
            throw new Error("Expected the field `establish_date` to be a primitive type in the JSON string but got " + data['establish_date']);
        }
        // ensure the json data is a string
        if (data['commencement_date'] && !(typeof data['commencement_date'] === 'string' || data['commencement_date'] instanceof String)) {
            throw new Error("Expected the field `commencement_date` to be a primitive type in the JSON string but got " + data['commencement_date']);
        }
        // ensure the json data is a string
        if (data['valid_period'] && !(typeof data['valid_period'] === 'string' || data['valid_period'] instanceof String)) {
            throw new Error("Expected the field `valid_period` to be a primitive type in the JSON string but got " + data['valid_period']);
        }
        // validate the optional field `register_address`
        if (data['register_address']) { // data not null
          if (!!MerchantKycAddress.validateJSON) {
            MerchantKycAddress.validateJSON(data['register_address']);
          }
        }
        // validate the optional field `legal_info`
        if (data['legal_info']) { // data not null
          if (!!MerchantKycPersonInfo.validateJSON) {
            MerchantKycPersonInfo.validateJSON(data['legal_info']);
          }
        }
        if (data['ubo_infos']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['ubo_infos'])) {
                throw new Error("Expected the field `ubo_infos` to be an array in the JSON data but got " + data['ubo_infos']);
            }
            // validate the optional field `ubo_infos` (array)
            for (const item of data['ubo_infos']) {
                MerchantKycPersonInfo.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['online_store_url'] && !(typeof data['online_store_url'] === 'string' || data['online_store_url'] instanceof String)) {
            throw new Error("Expected the field `online_store_url` to be a primitive type in the JSON string but got " + data['online_store_url']);
        }

        return true;
    }


}

MerchantKycCompanyInfo.RequiredProperties = ["company_type", "listed", "attachments", "operation_address", "identify_no", "company_name", "company_name_en", "establish_date", "commencement_date", "valid_period", "register_address", "legal_info", "ubo_infos"];

/**
 * @member {module:model/MerchantKycCompanyType} company_type
 */
MerchantKycCompanyInfo.prototype['company_type'] = undefined;

/**
 * Whether the company is listed.
 * @member {Boolean} listed
 */
MerchantKycCompanyInfo.prototype['listed'] = undefined;

/**
 * The attachments of the company.
 * @member {Array.<module:model/MerchantKycCompanyAttachment>} attachments
 */
MerchantKycCompanyInfo.prototype['attachments'] = undefined;

/**
 * @member {module:model/MerchantKycAddress} operation_address
 */
MerchantKycCompanyInfo.prototype['operation_address'] = undefined;

/**
 * The company identification number.
 * @member {String} identify_no
 */
MerchantKycCompanyInfo.prototype['identify_no'] = undefined;

/**
 * The company name in local language.
 * @member {String} company_name
 */
MerchantKycCompanyInfo.prototype['company_name'] = undefined;

/**
 * The company name in English.
 * @member {String} company_name_en
 */
MerchantKycCompanyInfo.prototype['company_name_en'] = undefined;

/**
 * The establishment date of the company.
 * @member {String} establish_date
 */
MerchantKycCompanyInfo.prototype['establish_date'] = undefined;

/**
 * The commencement date of the company.
 * @member {String} commencement_date
 */
MerchantKycCompanyInfo.prototype['commencement_date'] = undefined;

/**
 * The valid period of the company registration.
 * @member {String} valid_period
 */
MerchantKycCompanyInfo.prototype['valid_period'] = undefined;

/**
 * @member {module:model/MerchantKycAddress} register_address
 */
MerchantKycCompanyInfo.prototype['register_address'] = undefined;

/**
 * @member {module:model/MerchantKycPersonInfo} legal_info
 */
MerchantKycCompanyInfo.prototype['legal_info'] = undefined;

/**
 * The ultimate beneficial owner information.
 * @member {Array.<module:model/MerchantKycPersonInfo>} ubo_infos
 */
MerchantKycCompanyInfo.prototype['ubo_infos'] = undefined;

/**
 * The online store URL. Required when merchant type is B2B.
 * @member {String} online_store_url
 */
MerchantKycCompanyInfo.prototype['online_store_url'] = undefined;






export default MerchantKycCompanyInfo;

