/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MerchantKycAddress model module.
 * @module model/MerchantKycAddress
 */
class MerchantKycAddress {
    /**
     * Constructs a new <code>MerchantKycAddress</code>.
     * @alias module:model/MerchantKycAddress
     * @param country {String} The country.
     * @param state {String} The state or province.
     * @param city {String} The city.
     * @param postcode {String} The postal code.
     * @param line1 {String} The address line.
     */
    constructor(country, state, city, postcode, line1) { 
        
        MerchantKycAddress.initialize(this, country, state, city, postcode, line1);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, country, state, city, postcode, line1) { 
        obj['country'] = country;
        obj['state'] = state;
        obj['city'] = city;
        obj['postcode'] = postcode;
        obj['line1'] = line1;
    }

    /**
     * Constructs a <code>MerchantKycAddress</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantKycAddress} obj Optional instance to populate.
     * @return {module:model/MerchantKycAddress} The populated <code>MerchantKycAddress</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantKycAddress();

            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('postcode')) {
                obj['postcode'] = ApiClient.convertToType(data['postcode'], 'String');
            }
            if (data.hasOwnProperty('line1')) {
                obj['line1'] = ApiClient.convertToType(data['line1'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MerchantKycAddress</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MerchantKycAddress</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MerchantKycAddress.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['country'] && !(typeof data['country'] === 'string' || data['country'] instanceof String)) {
            throw new Error("Expected the field `country` to be a primitive type in the JSON string but got " + data['country']);
        }
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }
        // ensure the json data is a string
        if (data['city'] && !(typeof data['city'] === 'string' || data['city'] instanceof String)) {
            throw new Error("Expected the field `city` to be a primitive type in the JSON string but got " + data['city']);
        }
        // ensure the json data is a string
        if (data['postcode'] && !(typeof data['postcode'] === 'string' || data['postcode'] instanceof String)) {
            throw new Error("Expected the field `postcode` to be a primitive type in the JSON string but got " + data['postcode']);
        }
        // ensure the json data is a string
        if (data['line1'] && !(typeof data['line1'] === 'string' || data['line1'] instanceof String)) {
            throw new Error("Expected the field `line1` to be a primitive type in the JSON string but got " + data['line1']);
        }

        return true;
    }


}

MerchantKycAddress.RequiredProperties = ["country", "state", "city", "postcode", "line1"];

/**
 * The country.
 * @member {String} country
 */
MerchantKycAddress.prototype['country'] = undefined;

/**
 * The state or province.
 * @member {String} state
 */
MerchantKycAddress.prototype['state'] = undefined;

/**
 * The city.
 * @member {String} city
 */
MerchantKycAddress.prototype['city'] = undefined;

/**
 * The postal code.
 * @member {String} postcode
 */
MerchantKycAddress.prototype['postcode'] = undefined;

/**
 * The address line.
 * @member {String} line1
 */
MerchantKycAddress.prototype['line1'] = undefined;






export default MerchantKycAddress;

