/**
 * Cobo Wallet as a Service 2.0
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MpcTransferSourceUtxoInputsExcludedInputsInner from './MpcTransferSourceUtxoInputsExcludedInputsInner';
import MpcTransferSourceUtxoInputsIncludedInputsInner from './MpcTransferSourceUtxoInputsIncludedInputsInner';

/**
 * The MpcTransferSourceUtxoInputs model module.
 * @module model/MpcTransferSourceUtxoInputs
 * @version 0.1.0
 */
class MpcTransferSourceUtxoInputs {
    /**
     * Constructs a new <code>MpcTransferSourceUtxoInputs</code>.
     * @alias module:model/MpcTransferSourceUtxoInputs
     */
    constructor() { 
        
        MpcTransferSourceUtxoInputs.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MpcTransferSourceUtxoInputs</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MpcTransferSourceUtxoInputs} obj Optional instance to populate.
     * @return {module:model/MpcTransferSourceUtxoInputs} The populated <code>MpcTransferSourceUtxoInputs</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MpcTransferSourceUtxoInputs();

            if (data.hasOwnProperty('included_inputs')) {
                obj['included_inputs'] = ApiClient.convertToType(data['included_inputs'], [MpcTransferSourceUtxoInputsIncludedInputsInner]);
            }
            if (data.hasOwnProperty('excluded_inputs')) {
                obj['excluded_inputs'] = ApiClient.convertToType(data['excluded_inputs'], [MpcTransferSourceUtxoInputsExcludedInputsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MpcTransferSourceUtxoInputs</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MpcTransferSourceUtxoInputs</code>.
     */
    static validateJSON(data) {
        if (data['included_inputs']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['included_inputs'])) {
                throw new Error("Expected the field `included_inputs` to be an array in the JSON data but got " + data['included_inputs']);
            }
            // validate the optional field `included_inputs` (array)
            for (const item of data['included_inputs']) {
                MpcTransferSourceUtxoInputsIncludedInputsInner.validateJSON(item);
            };
        }
        if (data['excluded_inputs']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['excluded_inputs'])) {
                throw new Error("Expected the field `excluded_inputs` to be an array in the JSON data but got " + data['excluded_inputs']);
            }
            // validate the optional field `excluded_inputs` (array)
            for (const item of data['excluded_inputs']) {
                MpcTransferSourceUtxoInputsExcludedInputsInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/MpcTransferSourceUtxoInputsIncludedInputsInner>} included_inputs
 */
MpcTransferSourceUtxoInputs.prototype['included_inputs'] = undefined;

/**
 * @member {Array.<module:model/MpcTransferSourceUtxoInputsExcludedInputsInner>} excluded_inputs
 */
MpcTransferSourceUtxoInputs.prototype['excluded_inputs'] = undefined;






export default MpcTransferSourceUtxoInputs;

