/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentBankWithdrawalStatus from './PaymentBankWithdrawalStatus';

/**
 * The PaymentBankWithdrawalTimelineItem model module.
 * @module model/PaymentBankWithdrawalTimelineItem
 */
class PaymentBankWithdrawalTimelineItem {
    /**
     * Constructs a new <code>PaymentBankWithdrawalTimelineItem</code>.
     * @alias module:model/PaymentBankWithdrawalTimelineItem
     * @param status {module:model/PaymentBankWithdrawalStatus} 
     * @param timestamp {Number} The time when the bank withdrawal entered this status, represented as a UNIX timestamp in seconds.
     */
    constructor(status, timestamp) { 
        
        PaymentBankWithdrawalTimelineItem.initialize(this, status, timestamp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status, timestamp) { 
        obj['status'] = status;
        obj['timestamp'] = timestamp;
    }

    /**
     * Constructs a <code>PaymentBankWithdrawalTimelineItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentBankWithdrawalTimelineItem} obj Optional instance to populate.
     * @return {module:model/PaymentBankWithdrawalTimelineItem} The populated <code>PaymentBankWithdrawalTimelineItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentBankWithdrawalTimelineItem();

            if (data.hasOwnProperty('status')) {
                obj['status'] = PaymentBankWithdrawalStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentBankWithdrawalTimelineItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentBankWithdrawalTimelineItem</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PaymentBankWithdrawalTimelineItem.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

PaymentBankWithdrawalTimelineItem.RequiredProperties = ["status", "timestamp"];

/**
 * @member {module:model/PaymentBankWithdrawalStatus} status
 */
PaymentBankWithdrawalTimelineItem.prototype['status'] = undefined;

/**
 * The time when the bank withdrawal entered this status, represented as a UNIX timestamp in seconds.
 * @member {Number} timestamp
 */
PaymentBankWithdrawalTimelineItem.prototype['timestamp'] = undefined;






export default PaymentBankWithdrawalTimelineItem;

