/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MerchantKycCompanyInfo from './MerchantKycCompanyInfo';
import MerchantKycMerchantType from './MerchantKycMerchantType';
import MerchantKycPersonInfo from './MerchantKycPersonInfo';

/**
 * The SubmitMerchantKyc model module.
 * @module model/SubmitMerchantKyc
 */
class SubmitMerchantKyc {
    /**
     * Constructs a new <code>SubmitMerchantKyc</code>.
     * @alias module:model/SubmitMerchantKyc
     * @param merchant_type {module:model/MerchantKycMerchantType} 
     * @param country {String} The country/region of the merchant, in ISO 3166-1 alpha-3 format.
     * @param industry {Array.<String>} The industry categories of the merchant.
     */
    constructor(merchant_type, country, industry) { 
        
        SubmitMerchantKyc.initialize(this, merchant_type, country, industry);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, merchant_type, country, industry) { 
        obj['merchant_type'] = merchant_type;
        obj['country'] = country;
        obj['industry'] = industry;
    }

    /**
     * Constructs a <code>SubmitMerchantKyc</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubmitMerchantKyc} obj Optional instance to populate.
     * @return {module:model/SubmitMerchantKyc} The populated <code>SubmitMerchantKyc</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubmitMerchantKyc();

            if (data.hasOwnProperty('merchant_type')) {
                obj['merchant_type'] = MerchantKycMerchantType.constructFromObject(data['merchant_type']);
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('industry')) {
                obj['industry'] = ApiClient.convertToType(data['industry'], ['String']);
            }
            if (data.hasOwnProperty('company_info')) {
                obj['company_info'] = MerchantKycCompanyInfo.constructFromObject(data['company_info']);
            }
            if (data.hasOwnProperty('individual_info')) {
                obj['individual_info'] = MerchantKycPersonInfo.constructFromObject(data['individual_info']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubmitMerchantKyc</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubmitMerchantKyc</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SubmitMerchantKyc.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['country'] && !(typeof data['country'] === 'string' || data['country'] instanceof String)) {
            throw new Error("Expected the field `country` to be a primitive type in the JSON string but got " + data['country']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['industry'])) {
            throw new Error("Expected the field `industry` to be an array in the JSON data but got " + data['industry']);
        }
        // validate the optional field `company_info`
        if (data['company_info']) { // data not null
          if (!!MerchantKycCompanyInfo.validateJSON) {
            MerchantKycCompanyInfo.validateJSON(data['company_info']);
          }
        }
        // validate the optional field `individual_info`
        if (data['individual_info']) { // data not null
          if (!!MerchantKycPersonInfo.validateJSON) {
            MerchantKycPersonInfo.validateJSON(data['individual_info']);
          }
        }

        return true;
    }


}

SubmitMerchantKyc.RequiredProperties = ["merchant_type", "country", "industry"];

/**
 * @member {module:model/MerchantKycMerchantType} merchant_type
 */
SubmitMerchantKyc.prototype['merchant_type'] = undefined;

/**
 * The country/region of the merchant, in ISO 3166-1 alpha-3 format.
 * @member {String} country
 */
SubmitMerchantKyc.prototype['country'] = undefined;

/**
 * The industry categories of the merchant.
 * @member {Array.<String>} industry
 */
SubmitMerchantKyc.prototype['industry'] = undefined;

/**
 * @member {module:model/MerchantKycCompanyInfo} company_info
 */
SubmitMerchantKyc.prototype['company_info'] = undefined;

/**
 * @member {module:model/MerchantKycPersonInfo} individual_info
 */
SubmitMerchantKyc.prototype['individual_info'] = undefined;






export default SubmitMerchantKyc;

