/**
 * Cobo Wallet as a Service 2.0
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FeeType from './FeeType';
import TransactionEvmEip1559Fee from './TransactionEvmEip1559Fee';
import TransactionEvmLegacyFee from './TransactionEvmLegacyFee';
import TransactionFixedFee from './TransactionFixedFee';
import TransactionUtxoFee from './TransactionUtxoFee';

/**
 * The TransactionFee model module.
 * @module model/TransactionFee
 * @version 0.2.5
 */
class TransactionFee {
    /**
     * Constructs a new <code>TransactionFee</code>.
     * @alias module:model/TransactionFee
     * @param {(module:model/TransactionEvmEip1559Fee|module:model/TransactionEvmLegacyFee|module:model/TransactionFixedFee|module:model/TransactionUtxoFee)} instance The actual instance to initialize TransactionFee.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "TransactionEvmEip1559Fee") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                TransactionEvmEip1559Fee.validateJSON(instance); // throw an exception if no match
                // create TransactionEvmEip1559Fee from JS object
                this.actualInstance = TransactionEvmEip1559Fee.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into TransactionEvmEip1559Fee
            errorMessages.push("Failed to construct TransactionEvmEip1559Fee: " + err)
        }

        try {
            if (typeof instance === "TransactionEvmLegacyFee") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                TransactionEvmLegacyFee.validateJSON(instance); // throw an exception if no match
                // create TransactionEvmLegacyFee from JS object
                this.actualInstance = TransactionEvmLegacyFee.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into TransactionEvmLegacyFee
            errorMessages.push("Failed to construct TransactionEvmLegacyFee: " + err)
        }

        try {
            if (typeof instance === "TransactionUtxoFee") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                TransactionUtxoFee.validateJSON(instance); // throw an exception if no match
                // create TransactionUtxoFee from JS object
                this.actualInstance = TransactionUtxoFee.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into TransactionUtxoFee
            errorMessages.push("Failed to construct TransactionUtxoFee: " + err)
        }

        try {
            if (typeof instance === "TransactionFixedFee") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                TransactionFixedFee.validateJSON(instance); // throw an exception if no match
                // create TransactionFixedFee from JS object
                this.actualInstance = TransactionFixedFee.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into TransactionFixedFee
            errorMessages.push("Failed to construct TransactionFixedFee: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `TransactionFee` with oneOf schemas TransactionEvmEip1559Fee, TransactionEvmLegacyFee, TransactionFixedFee, TransactionUtxoFee. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `TransactionFee` with oneOf schemas TransactionEvmEip1559Fee, TransactionEvmLegacyFee, TransactionFixedFee, TransactionUtxoFee. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>TransactionFee</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransactionFee} obj Optional instance to populate.
     * @return {module:model/TransactionFee} The populated <code>TransactionFee</code> instance.
     */
    static constructFromObject(data, obj) {
        return new TransactionFee(data);
    }

    /**
     * Gets the actual instance, which can be <code>TransactionEvmEip1559Fee</code>, <code>TransactionEvmLegacyFee</code>, <code>TransactionFixedFee</code>, <code>TransactionUtxoFee</code>.
     * @return {(module:model/TransactionEvmEip1559Fee|module:model/TransactionEvmLegacyFee|module:model/TransactionFixedFee|module:model/TransactionUtxoFee)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>TransactionEvmEip1559Fee</code>, <code>TransactionEvmLegacyFee</code>, <code>TransactionFixedFee</code>, <code>TransactionUtxoFee</code>.
     * @param {(module:model/TransactionEvmEip1559Fee|module:model/TransactionEvmLegacyFee|module:model/TransactionFixedFee|module:model/TransactionUtxoFee)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = TransactionFee.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of TransactionFee from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/TransactionFee} An instance of TransactionFee.
     */
    static fromJSON = function(json_string){
        return TransactionFee.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/FeeType} fee_type
 */
TransactionFee.prototype['fee_type'] = undefined;

/**
 * The transaction fee.
 * @member {String} fee_used
 */
TransactionFee.prototype['fee_used'] = undefined;

/**
 * The gas units used in the transaction.
 * @member {String} gas_used
 */
TransactionFee.prototype['gas_used'] = undefined;

/**
 * The maximum priority fee, in wei. The maximum priority fee represents the highest amount of miner tips that you are willing to pay for your transaction.
 * @member {String} max_priority_fee
 */
TransactionFee.prototype['max_priority_fee'] = undefined;

/**
 * The base fee price of the chain, in wei.
 * @member {String} base_fee
 */
TransactionFee.prototype['base_fee'] = undefined;

/**
 * The gas limit. It represents the maximum number of gas units that you are willing to pay for the execution of a transaction or Ethereum Virtual Machine (EVM) operation. The gas unit cost of each operation varies.
 * @member {String} gas_limit
 * @default '21000'
 */
TransactionFee.prototype['gas_limit'] = '21000';

/**
 * The gas price, in wei. The gas price represents the amount of ETH that must be paid to validators for processing transactions.
 * @member {String} gas_price
 */
TransactionFee.prototype['gas_price'] = undefined;

/**
 * The fee rate in sat/vByte. The fee rate represents the satoshis you are willing to pay for each byte of data that your transaction will consume on the blockchain.
 * @member {String} fee_rate
 */
TransactionFee.prototype['fee_rate'] = undefined;

/**
 * The maximum fee that you are willing to pay for the transaction. The transaction will fail if the transaction fee exceeds the maximum fee.
 * @member {String} max_fee_amount
 */
TransactionFee.prototype['max_fee_amount'] = undefined;

/**
 * The token ID of the transaction fee.
 * @member {String} token_id
 */
TransactionFee.prototype['token_id'] = undefined;


TransactionFee.OneOf = ["TransactionEvmEip1559Fee", "TransactionEvmLegacyFee", "TransactionFixedFee", "TransactionUtxoFee"];

export default TransactionFee;

