/**
 * Cobo Wallet as a Service 2.0
 * Cobo WaaS 2.0 enables you to programmatically access Cobo's full suite of crypto wallet technologies with powerful and flexible access controls.  # Wallet technologies - Custodial Wallet - MPC Wallet - Smart Contract Wallet (Based on Safe{Wallet}) - Exchange Wallet  # Risk Control technologies - Workflow - Access Control List (ACL)  # Risk Control targets - Wallet Management   - User/team and their permission management   - Risk control configurations, e.g. whitelist, blacklist, rate-limiting etc. - Blockchain Interaction   - Crypto transfer   - Smart Contract Invocation  # Important HTTPS only. RESTful, resource oriented  # Get Started Set up your APIs or get authorization  # Authentication and Authorization CoboAuth  # Request and Response application/json  # Error Handling  ### Common error codes | Error Code | Description | | -- | -- |  ### API-specific error codes For error codes that are dedicated to a specific API, see the Error codes section in each API specification, for example, /v3/wallets.  # Rate and Usage Limiting  # Idempotent Request  # Pagination # Support [Developer Hub](https://cobo.com/developers) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CoboWaas2Api);
  }
}(this, function(expect, CoboWaas2Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CoboWaas2Api.MaxSendValue();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MaxSendValue', function() {
    it('should create an instance of MaxSendValue', function() {
      // uncomment below and update the code to test MaxSendValue
      //var instance = new CoboWaas2Api.MaxSendValue();
      //expect(instance).to.be.a(CoboWaas2Api.MaxSendValue);
    });

    it('should have the property token (base name: "token")', function() {
      // uncomment below and update the code to test the property token
      //var instance = new CoboWaas2Api.MaxSendValue();
      //expect(instance).to.be();
    });

    it('should have the property tokenDecimal (base name: "token_decimal")', function() {
      // uncomment below and update the code to test the property tokenDecimal
      //var instance = new CoboWaas2Api.MaxSendValue();
      //expect(instance).to.be();
    });

    it('should have the property feeToken (base name: "fee_token")', function() {
      // uncomment below and update the code to test the property feeToken
      //var instance = new CoboWaas2Api.MaxSendValue();
      //expect(instance).to.be();
    });

    it('should have the property feeDecimal (base name: "fee_decimal")', function() {
      // uncomment below and update the code to test the property feeDecimal
      //var instance = new CoboWaas2Api.MaxSendValue();
      //expect(instance).to.be();
    });

    it('should have the property maxSendValue (base name: "max_send_value")', function() {
      // uncomment below and update the code to test the property maxSendValue
      //var instance = new CoboWaas2Api.MaxSendValue();
      //expect(instance).to.be();
    });

    it('should have the property feePerByte (base name: "fee_per_byte")', function() {
      // uncomment below and update the code to test the property feePerByte
      //var instance = new CoboWaas2Api.MaxSendValue();
      //expect(instance).to.be();
    });

    it('should have the property feeValue (base name: "fee_value")', function() {
      // uncomment below and update the code to test the property feeValue
      //var instance = new CoboWaas2Api.MaxSendValue();
      //expect(instance).to.be();
    });

    it('should have the property gasPrice (base name: "gas_price")', function() {
      // uncomment below and update the code to test the property gasPrice
      //var instance = new CoboWaas2Api.MaxSendValue();
      //expect(instance).to.be();
    });

    it('should have the property gasLimit (base name: "gas_limit")', function() {
      // uncomment below and update the code to test the property gasLimit
      //var instance = new CoboWaas2Api.MaxSendValue();
      //expect(instance).to.be();
    });

  });

}));
