/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CoboWaas2);
  }
}(this, function(expect, CoboWaas2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CoboWaas2.PaymentBankWithdrawal();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PaymentBankWithdrawal', function() {
    it('should create an instance of PaymentBankWithdrawal', function() {
      // uncomment below and update the code to test PaymentBankWithdrawal
      //var instance = new CoboWaas2.PaymentBankWithdrawal();
      //expect(instance).to.be.a(CoboWaas2.PaymentBankWithdrawal);
    });

    it('should have the property bank_withdrawal_id (base name: "bank_withdrawal_id")', function() {
      // uncomment below and update the code to test the property bank_withdrawal_id
      //var instance = new CoboWaas2.PaymentBankWithdrawal();
      //expect(instance).to.be();
    });

    it('should have the property request_id (base name: "request_id")', function() {
      // uncomment below and update the code to test the property request_id
      //var instance = new CoboWaas2.PaymentBankWithdrawal();
      //expect(instance).to.be();
    });

    it('should have the property source_bank_account_id (base name: "source_bank_account_id")', function() {
      // uncomment below and update the code to test the property source_bank_account_id
      //var instance = new CoboWaas2.PaymentBankWithdrawal();
      //expect(instance).to.be();
    });

    it('should have the property target_bank_account_id (base name: "target_bank_account_id")', function() {
      // uncomment below and update the code to test the property target_bank_account_id
      //var instance = new CoboWaas2.PaymentBankWithdrawal();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new CoboWaas2.PaymentBankWithdrawal();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new CoboWaas2.PaymentBankWithdrawal();
      //expect(instance).to.be();
    });

    it('should have the property remark (base name: "remark")', function() {
      // uncomment below and update the code to test the property remark
      //var instance = new CoboWaas2.PaymentBankWithdrawal();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new CoboWaas2.PaymentBankWithdrawal();
      //expect(instance).to.be();
    });

    it('should have the property created_timestamp (base name: "created_timestamp")', function() {
      // uncomment below and update the code to test the property created_timestamp
      //var instance = new CoboWaas2.PaymentBankWithdrawal();
      //expect(instance).to.be();
    });

    it('should have the property failed_reason (base name: "failed_reason")', function() {
      // uncomment below and update the code to test the property failed_reason
      //var instance = new CoboWaas2.PaymentBankWithdrawal();
      //expect(instance).to.be();
    });

  });

}));
